controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\DefaultController::index

app_usuarios_index:
  path: /usuarios
  controller: App\Controller\UsuarioController::index

# filtrar

app_usuario_filtrar:
    path: '/usuarios/filtrar'
    controller: 'App\Controller\UsuarioController::filtrarUsuarios'
    methods: ['GET']

app_usuario_filtrar_pais:
    path: '/usuarios/filtrar-por-pais'
    controller: 'App\Controller\UsuarioController::filtrarPorPais'
    methods: ['GET']  # Ajusta los métodos según tus necesidades

app_habitaciones_index:
  path: /habitaciones
  controller: App\Controller\HabitacionController::index

app_habitaciones_filtrar:
  path: /habitaciones/filtrar
  controller: App\Controller\HabitacionController::filtrar

app_actividades_index:
  path: /actividades
  controller: App\Controller\ActividadesController::index

app_actividades_filtrar:
  path: /actividades/filtrar/{categoria}
  controller: App\Controller\ActividadesController::filtrarActividades

app_actividades_reservas.json:
  path: /actividades/reservas/{categoria}
  controller: App\Controller\ActividadesController::verReservas
  methods: ['GET']

