controllers:
    resource:
        path: ../src/Controller/
        namespace: App\Controller
    type: attribute

app_home:
    path: /
    controller: App\Controller\DefaultController::index

app_usuarios_index:
  path: /usuarios
  controller: App\Controller\UsuarioController::index

app_habitaciones_index:
  path: /habitaciones
  controller: App\Controller\HabitacionController::index

app_actividades_index:
  path: /actividades
  controller: App\Controller\ActividadesController::index

app_actividades_filtrar:
    path: '/actividades/filtrar/{categoria}'
    controller: 'App\Controller\ActividadesController::filtrarActividades'
